/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace GuardedExecutor {
  export type RequestStruct = {
    id: BytesLike;
    policyId: BytesLike;
    submitter: AddressLike;
    recipient: AddressLike;
    amount: BigNumberish;
    token: AddressLike;
    evidenceHash: BytesLike;
    storageRef: string;
    memo: string;
    status: BigNumberish;
    receiptId: BytesLike;
    createdAt: BigNumberish;
    resolvedAt: BigNumberish;
  };

  export type RequestStructOutput = [
    id: string,
    policyId: string,
    submitter: string,
    recipient: string,
    amount: bigint,
    token: string,
    evidenceHash: string,
    storageRef: string,
    memo: string,
    status: bigint,
    receiptId: string,
    createdAt: bigint,
    resolvedAt: bigint
  ] & {
    id: string;
    policyId: string;
    submitter: string;
    recipient: string;
    amount: bigint;
    token: string;
    evidenceHash: string;
    storageRef: string;
    memo: string;
    status: bigint;
    receiptId: string;
    createdAt: bigint;
    resolvedAt: bigint;
  };
}

export interface GuardedExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReviewer"
      | "approveRequest"
      | "ethBalance"
      | "getRequest"
      | "owner"
      | "policyRegistry"
      | "receiptRegistry"
      | "rejectRequest"
      | "removeReviewer"
      | "reviewers"
      | "submitRequest"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsReceived"
      | "OwnershipTransferred"
      | "RequestApproved"
      | "RequestExecuted"
      | "RequestFailed"
      | "RequestRejected"
      | "RequestSubmitted"
      | "ReviewerAdded"
      | "ReviewerRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReviewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approveRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "ethBalance",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "policyRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "receiptRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rejectRequest",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "removeReviewer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "reviewers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "submitRequest",
    values: [
      BytesLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      BytesLike,
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "approveRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "ethBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getRequest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "policyRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiptRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rejectRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeReviewer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reviewers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace FundsReceivedEvent {
  export type InputTuple = [from: AddressLike, amount: BigNumberish];
  export type OutputTuple = [from: string, amount: bigint];
  export interface OutputObject {
    from: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestApprovedEvent {
  export type InputTuple = [requestId: BytesLike, reviewer: AddressLike];
  export type OutputTuple = [requestId: string, reviewer: string];
  export interface OutputObject {
    requestId: string;
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestExecutedEvent {
  export type InputTuple = [requestId: BytesLike, receiptId: BytesLike];
  export type OutputTuple = [requestId: string, receiptId: string];
  export interface OutputObject {
    requestId: string;
    receiptId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestFailedEvent {
  export type InputTuple = [requestId: BytesLike, reason: string];
  export type OutputTuple = [requestId: string, reason: string];
  export interface OutputObject {
    requestId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestRejectedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    reviewer: AddressLike,
    reason: string
  ];
  export type OutputTuple = [
    requestId: string,
    reviewer: string,
    reason: string
  ];
  export interface OutputObject {
    requestId: string;
    reviewer: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestSubmittedEvent {
  export type InputTuple = [
    requestId: BytesLike,
    policyId: BytesLike,
    submitter: AddressLike,
    recipient: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    status: BigNumberish
  ];
  export type OutputTuple = [
    requestId: string,
    policyId: string,
    submitter: string,
    recipient: string,
    amount: bigint,
    token: string,
    status: bigint
  ];
  export interface OutputObject {
    requestId: string;
    policyId: string;
    submitter: string;
    recipient: string;
    amount: bigint;
    token: string;
    status: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerAddedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReviewerRemovedEvent {
  export type InputTuple = [reviewer: AddressLike];
  export type OutputTuple = [reviewer: string];
  export interface OutputObject {
    reviewer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface GuardedExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): GuardedExecutor;
  waitForDeployment(): Promise<this>;

  interface: GuardedExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReviewer: TypedContractMethod<
    [reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  approveRequest: TypedContractMethod<
    [requestId: BytesLike],
    [void],
    "nonpayable"
  >;

  ethBalance: TypedContractMethod<[], [bigint], "view">;

  getRequest: TypedContractMethod<
    [requestId: BytesLike],
    [GuardedExecutor.RequestStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  policyRegistry: TypedContractMethod<[], [string], "view">;

  receiptRegistry: TypedContractMethod<[], [string], "view">;

  rejectRequest: TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  removeReviewer: TypedContractMethod<
    [reviewer: AddressLike],
    [void],
    "nonpayable"
  >;

  reviewers: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  submitRequest: TypedContractMethod<
    [
      policyId: BytesLike,
      amount: BigNumberish,
      token: AddressLike,
      recipient: AddressLike,
      evidenceHash: BytesLike,
      storageRef: string,
      memo: string
    ],
    [string],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReviewer"
  ): TypedContractMethod<[reviewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "approveRequest"
  ): TypedContractMethod<[requestId: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "ethBalance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [GuardedExecutor.RequestStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "policyRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "receiptRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rejectRequest"
  ): TypedContractMethod<
    [requestId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeReviewer"
  ): TypedContractMethod<[reviewer: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reviewers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "submitRequest"
  ): TypedContractMethod<
    [
      policyId: BytesLike,
      amount: BigNumberish,
      token: AddressLike,
      recipient: AddressLike,
      evidenceHash: BytesLike,
      storageRef: string,
      memo: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "FundsReceived"
  ): TypedContractEvent<
    FundsReceivedEvent.InputTuple,
    FundsReceivedEvent.OutputTuple,
    FundsReceivedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RequestApproved"
  ): TypedContractEvent<
    RequestApprovedEvent.InputTuple,
    RequestApprovedEvent.OutputTuple,
    RequestApprovedEvent.OutputObject
  >;
  getEvent(
    key: "RequestExecuted"
  ): TypedContractEvent<
    RequestExecutedEvent.InputTuple,
    RequestExecutedEvent.OutputTuple,
    RequestExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RequestFailed"
  ): TypedContractEvent<
    RequestFailedEvent.InputTuple,
    RequestFailedEvent.OutputTuple,
    RequestFailedEvent.OutputObject
  >;
  getEvent(
    key: "RequestRejected"
  ): TypedContractEvent<
    RequestRejectedEvent.InputTuple,
    RequestRejectedEvent.OutputTuple,
    RequestRejectedEvent.OutputObject
  >;
  getEvent(
    key: "RequestSubmitted"
  ): TypedContractEvent<
    RequestSubmittedEvent.InputTuple,
    RequestSubmittedEvent.OutputTuple,
    RequestSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerAdded"
  ): TypedContractEvent<
    ReviewerAddedEvent.InputTuple,
    ReviewerAddedEvent.OutputTuple,
    ReviewerAddedEvent.OutputObject
  >;
  getEvent(
    key: "ReviewerRemoved"
  ): TypedContractEvent<
    ReviewerRemovedEvent.InputTuple,
    ReviewerRemovedEvent.OutputTuple,
    ReviewerRemovedEvent.OutputObject
  >;

  filters: {
    "FundsReceived(address,uint256)": TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;
    FundsReceived: TypedContractEvent<
      FundsReceivedEvent.InputTuple,
      FundsReceivedEvent.OutputTuple,
      FundsReceivedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RequestApproved(bytes32,address)": TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;
    RequestApproved: TypedContractEvent<
      RequestApprovedEvent.InputTuple,
      RequestApprovedEvent.OutputTuple,
      RequestApprovedEvent.OutputObject
    >;

    "RequestExecuted(bytes32,bytes32)": TypedContractEvent<
      RequestExecutedEvent.InputTuple,
      RequestExecutedEvent.OutputTuple,
      RequestExecutedEvent.OutputObject
    >;
    RequestExecuted: TypedContractEvent<
      RequestExecutedEvent.InputTuple,
      RequestExecutedEvent.OutputTuple,
      RequestExecutedEvent.OutputObject
    >;

    "RequestFailed(bytes32,string)": TypedContractEvent<
      RequestFailedEvent.InputTuple,
      RequestFailedEvent.OutputTuple,
      RequestFailedEvent.OutputObject
    >;
    RequestFailed: TypedContractEvent<
      RequestFailedEvent.InputTuple,
      RequestFailedEvent.OutputTuple,
      RequestFailedEvent.OutputObject
    >;

    "RequestRejected(bytes32,address,string)": TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;
    RequestRejected: TypedContractEvent<
      RequestRejectedEvent.InputTuple,
      RequestRejectedEvent.OutputTuple,
      RequestRejectedEvent.OutputObject
    >;

    "RequestSubmitted(bytes32,bytes32,address,address,uint256,address,uint8)": TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;
    RequestSubmitted: TypedContractEvent<
      RequestSubmittedEvent.InputTuple,
      RequestSubmittedEvent.OutputTuple,
      RequestSubmittedEvent.OutputObject
    >;

    "ReviewerAdded(address)": TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;
    ReviewerAdded: TypedContractEvent<
      ReviewerAddedEvent.InputTuple,
      ReviewerAddedEvent.OutputTuple,
      ReviewerAddedEvent.OutputObject
    >;

    "ReviewerRemoved(address)": TypedContractEvent<
      ReviewerRemovedEvent.InputTuple,
      ReviewerRemovedEvent.OutputTuple,
      ReviewerRemovedEvent.OutputObject
    >;
    ReviewerRemoved: TypedContractEvent<
      ReviewerRemovedEvent.InputTuple,
      ReviewerRemovedEvent.OutputTuple,
      ReviewerRemovedEvent.OutputObject
    >;
  };
}
