/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PolicyRegistry {
  export type PolicyStruct = {
    id: BytesLike;
    name: string;
    maxAutoAmount: BigNumberish;
    requireManualReviewAbove: BigNumberish;
    requireWhitelist: boolean;
    active: boolean;
    owner: AddressLike;
    createdAt: BigNumberish;
    updatedAt: BigNumberish;
  };

  export type PolicyStructOutput = [
    id: string,
    name: string,
    maxAutoAmount: bigint,
    requireManualReviewAbove: bigint,
    requireWhitelist: boolean,
    active: boolean,
    owner: string,
    createdAt: bigint,
    updatedAt: bigint
  ] & {
    id: string;
    name: string;
    maxAutoAmount: bigint;
    requireManualReviewAbove: bigint;
    requireWhitelist: boolean;
    active: boolean;
    owner: string;
    createdAt: bigint;
    updatedAt: bigint;
  };
}

export interface PolicyRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addToWhitelist"
      | "checkPolicy"
      | "getOwnerPolicies"
      | "getPolicy"
      | "isWhitelisted"
      | "registerPolicy"
      | "removeFromWhitelist"
      | "setActive"
      | "updatePolicy"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "PolicyActiveChanged"
      | "PolicyRegistered"
      | "PolicyUpdated"
      | "WhitelistUpdated"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addToWhitelist",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPolicy",
    values: [BytesLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOwnerPolicies",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getPolicy",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isWhitelisted",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "registerPolicy",
    values: [string, BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "removeFromWhitelist",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setActive",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePolicy",
    values: [BytesLike, BigNumberish, BigNumberish, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "addToWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOwnerPolicies",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPolicy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isWhitelisted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerPolicy",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeFromWhitelist",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setActive", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updatePolicy",
    data: BytesLike
  ): Result;
}

export namespace PolicyActiveChangedEvent {
  export type InputTuple = [policyId: BytesLike, active: boolean];
  export type OutputTuple = [policyId: string, active: boolean];
  export interface OutputObject {
    policyId: string;
    active: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyRegisteredEvent {
  export type InputTuple = [
    policyId: BytesLike,
    owner: AddressLike,
    name: string
  ];
  export type OutputTuple = [policyId: string, owner: string, name: string];
  export interface OutputObject {
    policyId: string;
    owner: string;
    name: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PolicyUpdatedEvent {
  export type InputTuple = [policyId: BytesLike];
  export type OutputTuple = [policyId: string];
  export interface OutputObject {
    policyId: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WhitelistUpdatedEvent {
  export type InputTuple = [
    policyId: BytesLike,
    addr: AddressLike,
    allowed: boolean
  ];
  export type OutputTuple = [policyId: string, addr: string, allowed: boolean];
  export interface OutputObject {
    policyId: string;
    addr: string;
    allowed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PolicyRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): PolicyRegistry;
  waitForDeployment(): Promise<this>;

  interface: PolicyRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addToWhitelist: TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  checkPolicy: TypedContractMethod<
    [policyId: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [
      [boolean, boolean, string] & {
        autoApprove: boolean;
        requiresReview: boolean;
        reason: string;
      }
    ],
    "view"
  >;

  getOwnerPolicies: TypedContractMethod<
    [owner: AddressLike],
    [string[]],
    "view"
  >;

  getPolicy: TypedContractMethod<
    [policyId: BytesLike],
    [PolicyRegistry.PolicyStructOutput],
    "view"
  >;

  isWhitelisted: TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;

  registerPolicy: TypedContractMethod<
    [
      name: string,
      maxAutoAmount: BigNumberish,
      requireManualReviewAbove: BigNumberish,
      requireWhitelist: boolean
    ],
    [string],
    "nonpayable"
  >;

  removeFromWhitelist: TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;

  setActive: TypedContractMethod<
    [policyId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;

  updatePolicy: TypedContractMethod<
    [
      policyId: BytesLike,
      maxAutoAmount: BigNumberish,
      requireManualReviewAbove: BigNumberish,
      requireWhitelist: boolean
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addToWhitelist"
  ): TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkPolicy"
  ): TypedContractMethod<
    [policyId: BytesLike, recipient: AddressLike, amount: BigNumberish],
    [
      [boolean, boolean, string] & {
        autoApprove: boolean;
        requiresReview: boolean;
        reason: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOwnerPolicies"
  ): TypedContractMethod<[owner: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getPolicy"
  ): TypedContractMethod<
    [policyId: BytesLike],
    [PolicyRegistry.PolicyStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isWhitelisted"
  ): TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerPolicy"
  ): TypedContractMethod<
    [
      name: string,
      maxAutoAmount: BigNumberish,
      requireManualReviewAbove: BigNumberish,
      requireWhitelist: boolean
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeFromWhitelist"
  ): TypedContractMethod<
    [policyId: BytesLike, addr: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setActive"
  ): TypedContractMethod<
    [policyId: BytesLike, active: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updatePolicy"
  ): TypedContractMethod<
    [
      policyId: BytesLike,
      maxAutoAmount: BigNumberish,
      requireManualReviewAbove: BigNumberish,
      requireWhitelist: boolean
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "PolicyActiveChanged"
  ): TypedContractEvent<
    PolicyActiveChangedEvent.InputTuple,
    PolicyActiveChangedEvent.OutputTuple,
    PolicyActiveChangedEvent.OutputObject
  >;
  getEvent(
    key: "PolicyRegistered"
  ): TypedContractEvent<
    PolicyRegisteredEvent.InputTuple,
    PolicyRegisteredEvent.OutputTuple,
    PolicyRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "PolicyUpdated"
  ): TypedContractEvent<
    PolicyUpdatedEvent.InputTuple,
    PolicyUpdatedEvent.OutputTuple,
    PolicyUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "WhitelistUpdated"
  ): TypedContractEvent<
    WhitelistUpdatedEvent.InputTuple,
    WhitelistUpdatedEvent.OutputTuple,
    WhitelistUpdatedEvent.OutputObject
  >;

  filters: {
    "PolicyActiveChanged(bytes32,bool)": TypedContractEvent<
      PolicyActiveChangedEvent.InputTuple,
      PolicyActiveChangedEvent.OutputTuple,
      PolicyActiveChangedEvent.OutputObject
    >;
    PolicyActiveChanged: TypedContractEvent<
      PolicyActiveChangedEvent.InputTuple,
      PolicyActiveChangedEvent.OutputTuple,
      PolicyActiveChangedEvent.OutputObject
    >;

    "PolicyRegistered(bytes32,address,string)": TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;
    PolicyRegistered: TypedContractEvent<
      PolicyRegisteredEvent.InputTuple,
      PolicyRegisteredEvent.OutputTuple,
      PolicyRegisteredEvent.OutputObject
    >;

    "PolicyUpdated(bytes32)": TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;
    PolicyUpdated: TypedContractEvent<
      PolicyUpdatedEvent.InputTuple,
      PolicyUpdatedEvent.OutputTuple,
      PolicyUpdatedEvent.OutputObject
    >;

    "WhitelistUpdated(bytes32,address,bool)": TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
    WhitelistUpdated: TypedContractEvent<
      WhitelistUpdatedEvent.InputTuple,
      WhitelistUpdatedEvent.OutputTuple,
      WhitelistUpdatedEvent.OutputObject
    >;
  };
}
