/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ReceiptRegistry {
  export type ReceiptStruct = {
    id: BytesLike;
    requestId: BytesLike;
    evidenceHash: BytesLike;
    txHash: BytesLike;
    status: BigNumberish;
    executor: AddressLike;
    submitter: AddressLike;
    amount: BigNumberish;
    token: AddressLike;
    recipient: AddressLike;
    createdAt: BigNumberish;
    confirmedAt: BigNumberish;
    storageRef: string;
    failReason: string;
  };

  export type ReceiptStructOutput = [
    id: string,
    requestId: string,
    evidenceHash: string,
    txHash: string,
    status: bigint,
    executor: string,
    submitter: string,
    amount: bigint,
    token: string,
    recipient: string,
    createdAt: bigint,
    confirmedAt: bigint,
    storageRef: string,
    failReason: string
  ] & {
    id: string;
    requestId: string;
    evidenceHash: string;
    txHash: string;
    status: bigint;
    executor: string;
    submitter: string;
    amount: bigint;
    token: string;
    recipient: string;
    createdAt: bigint;
    confirmedAt: bigint;
    storageRef: string;
    failReason: string;
  };
}

export interface ReceiptRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "authorizeExecutor"
      | "authorizedExecutors"
      | "confirmReceipt"
      | "createReceipt"
      | "failReceipt"
      | "getReceipt"
      | "getReceiptByRequest"
      | "owner"
      | "requestToReceipt"
      | "revokeExecutor"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ExecutorAuthorized"
      | "ExecutorRevoked"
      | "OwnershipTransferred"
      | "ReceiptConfirmed"
      | "ReceiptCreated"
      | "ReceiptFailed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "authorizeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizedExecutors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "confirmReceipt",
    values: [BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createReceipt",
    values: [
      BytesLike,
      BytesLike,
      AddressLike,
      BigNumberish,
      AddressLike,
      AddressLike,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "failReceipt",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getReceiptByRequest",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "requestToReceipt",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeExecutor",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "authorizeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizedExecutors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confirmReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "failReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getReceipt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getReceiptByRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "requestToReceipt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeExecutor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ExecutorAuthorizedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ExecutorRevokedEvent {
  export type InputTuple = [executor: AddressLike];
  export type OutputTuple = [executor: string];
  export interface OutputObject {
    executor: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [oldOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [oldOwner: string, newOwner: string];
  export interface OutputObject {
    oldOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptConfirmedEvent {
  export type InputTuple = [receiptId: BytesLike, txHash: BytesLike];
  export type OutputTuple = [receiptId: string, txHash: string];
  export interface OutputObject {
    receiptId: string;
    txHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptCreatedEvent {
  export type InputTuple = [
    receiptId: BytesLike,
    requestId: BytesLike,
    submitter: AddressLike,
    amount: BigNumberish,
    token: AddressLike,
    recipient: AddressLike
  ];
  export type OutputTuple = [
    receiptId: string,
    requestId: string,
    submitter: string,
    amount: bigint,
    token: string,
    recipient: string
  ];
  export interface OutputObject {
    receiptId: string;
    requestId: string;
    submitter: string;
    amount: bigint;
    token: string;
    recipient: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReceiptFailedEvent {
  export type InputTuple = [receiptId: BytesLike, reason: string];
  export type OutputTuple = [receiptId: string, reason: string];
  export interface OutputObject {
    receiptId: string;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReceiptRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ReceiptRegistry;
  waitForDeployment(): Promise<this>;

  interface: ReceiptRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  authorizeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  authorizedExecutors: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  confirmReceipt: TypedContractMethod<
    [receiptId: BytesLike, txHash: BytesLike],
    [void],
    "nonpayable"
  >;

  createReceipt: TypedContractMethod<
    [
      requestId: BytesLike,
      evidenceHash: BytesLike,
      submitter: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      recipient: AddressLike,
      storageRef: string
    ],
    [string],
    "nonpayable"
  >;

  failReceipt: TypedContractMethod<
    [receiptId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;

  getReceipt: TypedContractMethod<
    [receiptId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;

  getReceiptByRequest: TypedContractMethod<
    [requestId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  requestToReceipt: TypedContractMethod<[arg0: BytesLike], [string], "view">;

  revokeExecutor: TypedContractMethod<
    [executor: AddressLike],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "authorizeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizedExecutors"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "confirmReceipt"
  ): TypedContractMethod<
    [receiptId: BytesLike, txHash: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createReceipt"
  ): TypedContractMethod<
    [
      requestId: BytesLike,
      evidenceHash: BytesLike,
      submitter: AddressLike,
      amount: BigNumberish,
      token: AddressLike,
      recipient: AddressLike,
      storageRef: string
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "failReceipt"
  ): TypedContractMethod<
    [receiptId: BytesLike, reason: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getReceipt"
  ): TypedContractMethod<
    [receiptId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getReceiptByRequest"
  ): TypedContractMethod<
    [requestId: BytesLike],
    [ReceiptRegistry.ReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "requestToReceipt"
  ): TypedContractMethod<[arg0: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "revokeExecutor"
  ): TypedContractMethod<[executor: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ExecutorAuthorized"
  ): TypedContractEvent<
    ExecutorAuthorizedEvent.InputTuple,
    ExecutorAuthorizedEvent.OutputTuple,
    ExecutorAuthorizedEvent.OutputObject
  >;
  getEvent(
    key: "ExecutorRevoked"
  ): TypedContractEvent<
    ExecutorRevokedEvent.InputTuple,
    ExecutorRevokedEvent.OutputTuple,
    ExecutorRevokedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptConfirmed"
  ): TypedContractEvent<
    ReceiptConfirmedEvent.InputTuple,
    ReceiptConfirmedEvent.OutputTuple,
    ReceiptConfirmedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptCreated"
  ): TypedContractEvent<
    ReceiptCreatedEvent.InputTuple,
    ReceiptCreatedEvent.OutputTuple,
    ReceiptCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ReceiptFailed"
  ): TypedContractEvent<
    ReceiptFailedEvent.InputTuple,
    ReceiptFailedEvent.OutputTuple,
    ReceiptFailedEvent.OutputObject
  >;

  filters: {
    "ExecutorAuthorized(address)": TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;
    ExecutorAuthorized: TypedContractEvent<
      ExecutorAuthorizedEvent.InputTuple,
      ExecutorAuthorizedEvent.OutputTuple,
      ExecutorAuthorizedEvent.OutputObject
    >;

    "ExecutorRevoked(address)": TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;
    ExecutorRevoked: TypedContractEvent<
      ExecutorRevokedEvent.InputTuple,
      ExecutorRevokedEvent.OutputTuple,
      ExecutorRevokedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReceiptConfirmed(bytes32,bytes32)": TypedContractEvent<
      ReceiptConfirmedEvent.InputTuple,
      ReceiptConfirmedEvent.OutputTuple,
      ReceiptConfirmedEvent.OutputObject
    >;
    ReceiptConfirmed: TypedContractEvent<
      ReceiptConfirmedEvent.InputTuple,
      ReceiptConfirmedEvent.OutputTuple,
      ReceiptConfirmedEvent.OutputObject
    >;

    "ReceiptCreated(bytes32,bytes32,address,uint256,address,address)": TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;
    ReceiptCreated: TypedContractEvent<
      ReceiptCreatedEvent.InputTuple,
      ReceiptCreatedEvent.OutputTuple,
      ReceiptCreatedEvent.OutputObject
    >;

    "ReceiptFailed(bytes32,string)": TypedContractEvent<
      ReceiptFailedEvent.InputTuple,
      ReceiptFailedEvent.OutputTuple,
      ReceiptFailedEvent.OutputObject
    >;
    ReceiptFailed: TypedContractEvent<
      ReceiptFailedEvent.InputTuple,
      ReceiptFailedEvent.OutputTuple,
      ReceiptFailedEvent.OutputObject
    >;
  };
}
